= Fabric8 Recommender

image:https://ci.centos.org/buildStatus/icon?job=devtools-fabric8-recommender-npm-publish-build-master[build, link="https://ci.centos.org/job/devtools-fabric8-recommender-npm-publish-build-master"]
image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic%20release-b4d455.svg[Semantic Release, link="https://github.com/semantic-release/semantic-release"]

**Fabric8 Recommender is a stack analysis feature.**


== Build

* Pre-requisites:
- node v8.9.1+ (required by anuglar-cli 6+)
- npm 5.5.1

This angular library is built using link:https://github.com/angular/angular-cli/wiki[angular-cli].
The main application is the demo app. The library source is under link:/projects/fabric8-stack-analysis-ui[/projects/fabric8-stack-analysis-ui].

* Install the dependencies

```
npm i
```

* Build library & demo app
```
npm run build
```

* Run the library tests

```
npm test
```

> NOTE: to run the library test in watch mode: `npm run test:lib:dev`


== Running the demo

To work with stack analysis demo, targeting PROD backend services:

 $ npm install; npm run build

Then, start the app with:

 $ npm start

Open your browser:

```

http://localhost:4200/#/analyze/<STACK_ID>?api_data={
    "access_token": "",
    "route_config": {
        "api_url": "https://recommender.api.openshift.io/"
    }
}

```

To get OSIO-TOKEN follow below steps :

1. Login to https://openshift.io/[OSIO]

2. Go to profile view

3. Edit Profile

4. Copy token


NOTE : STACK_ID is the ID of any stack analyses in OpenShift.io (can be fetched from network tab).

== Release

Semantic release are done via fabric8cd using `semantic-release`.
- merging each PR will result with an automatic build of master
- and a release apatch, minor or major version. You should use correct link:https://github.com/semantic-release/semantic-release#commit-message-format[commit message].

To test a distribution package:
```
npm run package
```
will generate `fabric8-stack-analysis-ui-0.0.1.tgz` in `dist/fabric8-stack-analysis-ui` folder.
```
npm install fabric8-stack-analysis-ui-0.0.1.tgz
```
to test your distribution within your app.
== Contributing

The development guide is part of the link:./CONTRIBUTING.adoc[contributors'
instructions]. Please check it out in order to contribute to this project. 
