export const environment = {
  production: true,
  STACK_API_TOKEN: '%STACK_API_TOKEN%',
  FABRIC8_WIT_API_URL: '%FABRIC8_WIT_API_URL%',
  FABRIC8_REALM: '%FABRIC8_REALM%',
  FABRIC8_RECOMMENDER_API_URL: '%FABRIC8_RECOMMENDER_API_URL%'
};
